name: Roboskel website deploy 

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          target_path: /
          keep_history: true
          commit_author: gstavrinos
